version: '3'
services:
    postgres:
        image: postgres:14
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
        volumes:
            - /home/${USER}/airflow-postgres-database/:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready -d db -U airflow"]
            interval: 5s
            retries: 5
        ports:
          - "5432:5432"
        restart: always
    scheduler:
        build: .
        command: poetry run /app/airflow/scheduler_entrypoint.sh
        restart: always
        depends_on:
            - postgres
        environment:
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
            - AIRFLOW__CORE__LOAD_EXAMPLES=false
        volumes:
            - ./dags:/app/airflow/dags
            - /home/${USER}/airflow-data:/app/airflow/data
            - /home/${USER}/airflow-logs:/app/airflow/logs
            - ./dbt_suretbon:/app/airflow/dbt_suretbon
    webserver:
        build: .
        command: poetry run /app/airflow/entrypoint.sh
        restart: always
        depends_on:
            - postgres
            - scheduler
        environment:
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - AIRFLOW_ADMIN_1_USERNAME=${AIRFLOW_ADMIN_1_USERNAME}
            - AIRFLOW_ADMIN_1_PASSWORD=${AIRFLOW_ADMIN_1_PASSWORD}
            - AIRFLOW_ADMIN_1_EMAIL=${AIRFLOW_ADMIN_1_EMAIL}
            - AIRFLOW_ADMIN_1_FIRST_NAME=${AIRFLOW_ADMIN_1_FIRST_NAME}
            - AIRFLOW_ADMIN_1_LAST_NAME=${AIRFLOW_ADMIN_1_LAST_NAME}
            - AIRFLOW_ADMIN_2_USERNAME=${AIRFLOW_ADMIN_2_USERNAME}
            - AIRFLOW_ADMIN_2_PASSWORD=${AIRFLOW_ADMIN_2_PASSWORD}
            - AIRFLOW_ADMIN_2_EMAIL=${AIRFLOW_ADMIN_2_EMAIL}
            - AIRFLOW_ADMIN_2_FIRST_NAME=${AIRFLOW_ADMIN_2_FIRST_NAME}
            - AIRFLOW_ADMIN_2_LAST_NAME=${AIRFLOW_ADMIN_2_LAST_NAME}
            - AIRFLOW_ADMIN_3_USERNAME=${AIRFLOW_ADMIN_3_USERNAME}
            - AIRFLOW_ADMIN_3_PASSWORD=${AIRFLOW_ADMIN_3_PASSWORD}
            - AIRFLOW_ADMIN_3_EMAIL=${AIRFLOW_ADMIN_3_EMAIL}
            - AIRFLOW_ADMIN_3_FIRST_NAME=${AIRFLOW_ADMIN_3_FIRST_NAME}
            - AIRFLOW_ADMIN_3_LAST_NAME=${AIRFLOW_ADMIN_3_LAST_NAME}
            - AIRFLOW_ADMIN_4_USERNAME=${AIRFLOW_ADMIN_4_USERNAME}
            - AIRFLOW_ADMIN_4_PASSWORD=${AIRFLOW_ADMIN_4_PASSWORD}
            - AIRFLOW_ADMIN_4_EMAIL=${AIRFLOW_ADMIN_4_EMAIL}
            - AIRFLOW_ADMIN_4_FIRST_NAME=${AIRFLOW_ADMIN_4_FIRST_NAME}
            - AIRFLOW_ADMIN_4_LAST_NAME=${AIRFLOW_ADMIN_4_LAST_NAME}
        volumes:
            - ./dags:/app/airflow/dags
            - /home/${USER}/airflow-data:/app/airflow/data
            - /home/${USER}/airflow-logs:/app/airflow/logs
        ports:
            - "8080:8080"
        healthcheck:
            test: ["CMD-SHELL", "[ -f /home/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3