#!/usr/bin/env bash
airflow db upgrade
airflow users create -r Admin -u $AIRFLOW_ADMIN_1_USERNAME -p $AIRFLOW_ADMIN_1_PASSWORD -e $AIRFLOW_ADMIN_1_EMAIL -f $AIRFLOW_ADMIN_1_FIRST_NAME -l $AIRFLOW_ADMIN_1_LAST_NAME
airflow users create -r Admin -u $AIRFLOW_ADMIN_2_USERNAME -p $AIRFLOW_ADMIN_2_PASSWORD -e $AIRFLOW_ADMIN_2_EMAIL -f $AIRFLOW_ADMIN_2_FIRST_NAME -l $AIRFLOW_ADMIN_2_LAST_NAME
airflow users create -r Admin -u $AIRFLOW_ADMIN_3_USERNAME -p $AIRFLOW_ADMIN_3_PASSWORD -e $AIRFLOW_ADMIN_3_EMAIL -f $AIRFLOW_ADMIN_3_FIRST_NAME -l $AIRFLOW_ADMIN_3_LAST_NAME
airflow users create -r Admin -u $AIRFLOW_ADMIN_4_USERNAME -p $AIRFLOW_ADMIN_4_PASSWORD -e $AIRFLOW_ADMIN_4_EMAIL -f $AIRFLOW_ADMIN_4_FIRST_NAME -l $AIRFLOW_ADMIN_4_LAST_NAME
airflow webserver