select
  trim(name) as name,
  trim(type) as type,
  trim(operator) as operator,
  trim(brand) as brand,
  trim(cuisine) as cuisine,
  trim(vegetarian) as vegetarian,
  trim(vegan) as vegan,
  trim(opening_hours) as opening_hours,
  trim(wheelchair) as wheelchair,
  trim(delivery) as delivery,
  trim(takeaway) as takeaway,
  trim(drive_through) as drive_through,
  trim(internet_access) as internet_access,
  capacity,
  safe_cast(stars as float64) as stars,
  trim(smoking) as smoking,
  trim(wikidata) as wikidata,
  trim(siret) as siret,
  trim(phone) as phone,
  trim(website) as website,
  trim(facebook) as facebook,
  meta_geo_point as meta_geo_point
 from
  `algebraic-link-440513-f9.raw.osm-france-food-service`
